### PR TITLE
Do not manually GC

### PR DESCRIPTION
**Pull request by NthPortal**
Do not manually GC, as it is very very expensive.

### CODE REVIEW

**Comment by SuperCoder7979** [comment]
It actually does fix some leaking memory issues so it's needed here.

**Comment by Devan-Kerman** [comment]
doubt

**Comment by Devan-Kerman** [comment]
ok, come at me bro

**Comment by ramidzkh** [comment]
HOLD HIM BACK BROS, HOLD HIM BACK

> @SuperCoder7979 locked as **too heated** and limited conversation to collaborators 20 seconds ago

**Comment by NthPortal** [comment]
I am skeptical of the ability of `System.gc()` to fix a memory leak, as (by definition) a memory leak means you are holding onto one or more references (and they are thus "reachable"), but the garbage collector is only allowed to free unreachable objects.

**Comment by SuperCoder7979** [comment]
Yeah.... as discussed on discord, I don't know how it fixes it either, but a user was pregenerating a large area and ran out of memory, but stopped having those issues once the explicit gc was enabled. It's strange and I don't know why it happens, it just does.

**Pull request closed without merging**
